### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [sirherrbatka/vellum-binary#1] opened 2023-02-11 21:17 UTC
Building with SBCL 2.3.1.67-d262a01cc / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id 7987e755fffbfe7eca84147729bfd5702faec38b

*vellum-binary* fails to build with the following error:

```
; caught ERROR:
;   READ error during COMPILE-FILE: Symbol "DECODE-OBJECT" not found in the CONSPACK package. Line: 309, Column: 33, File-Position: 12585 Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/quicklisp/quicklisp-controller/dist/build-cache/vellum-binary/c96ef62607ccaa9d894c474bc650a05f6271f152/vellum-binary-20230211-git/source/code.lisp" {10212566D3}>
...
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1040660073}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "vellum-binary" "code">

```

[Full log here](http://report.quicklisp.org/2023-02-11/failure-report/vellum-binary.html)

**Comment by sirherrbatka** [comment] 2023-02-16 09:41
Caused by changes in cl-conspack. Fixed now.

**Closed as completed by sirherrbatka** 2023-02-16 09:41 UTC
